### ISSUE TITLE
please support bower

### ISSUE THREAD

**Issue by sargin48** [flot/flot#1410] opened 2015-02-26 10:30 UTC
please support bower

users cant install with
cmd ->
bower install jquery.flot

**Comment by jlbooker** [comment] 2015-06-03 12:45
Try `bower install flot --save`

**Comment by camilonova** [comment] 2015-06-24 22:44
I can confirm it works, this issue can be closed.

**Comment by sandermarechal** [comment] 2015-07-21 09:56
This does not work. The component.json user "Flot" with a capital F as the name. Bower refuses to parse this:

bower flot#0.8.3                     EINVALID Failed to read /tmp/sander/bower/flot-17967-iay3ei/component.json

**Comment by jlbooker** [comment] 2015-07-21 13:42
@sandermarechal the previous command works for me: `bower install flot --save`

My bower.json dependency section looks like:
```
"dependencies": {
    "typeahead.js": "0.11.*",
    "flot": "~0.8.3"
  }
```

You should be using all lower-case letters in the name `flot`.

**Comment by sandermarechal** [comment] 2015-07-27 15:30
@jlbooker What version of Bower are you using? I have a lowercase "flot" specified in my own bower.json. The problem is the component.json in flot's repository that specifies it using a captial F.

**Comment by jlbooker** [comment] 2015-07-27 16:42
`bower --version` says `1.4.1`, which seems to be the current release.

**Comment by sandermarechal** [comment] 2015-08-05 13:22
Not sure what was causing it, but it seems to work now. You can close this.

**Closed** 2019-02-14 16:10 UTC
