### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by draptik** [flot/flot#1430] opened 2015-04-28 23:16 UTC
I'm considering to include this library in a project.

BUT the last commit to the master branch is a year old. Is this project still maintained / under active development? Also, there are many old pull request, which have never been merged.

Curious..

**Comment by 153957** [comment] 2015-05-12 13:01
Some newer commits are in the `0.9-work` branch and this is a duplicate of issue #1390.

**Comment by draptik** [comment] 2015-05-12 21:07
Good to hear that this project is under active development!

And thanks for the pointer (I was searching the issues tracker with 'active', 'live', not 'dead') to the duplicate as well as the work branch.

Is there an estimated release date for 0.9?

**Comment by 153957** [comment] 2015-05-12 21:23
Unfortunately, as you can read in #1390, the person that showed an interest in working on flot doesn't seem to have time after all.. so no estimated date at the moment..

**Comment by draptik** [comment] 2015-05-12 21:27
I understand.

Should future pull requests be targeting the master branch or the 0.9 branch? How stable is the 0.9 branch?

**Comment by upcesar** [comment] 2016-02-11 15:03
Hello. I've added a new issue #1486 related with translation, since I don't know whether I am the only one with this problem. Any comment would be welcome.

Thanks.

**Comment by Beakerboy** [comment] 2019-02-14 16:02
Project is once again active.

**Closed by Beakerboy** 2019-02-14 16:02 UTC
