### ISSUE TITLE
noColumns in API documentation but not implemented.

### ISSUE THREAD

**Issue by jondbennett** [flot/flot#1677] opened 2019-07-24 14:03 UTC
the noColumns option for the legend is in the API documentation but not implemented.
Should it be re-implemented or removed from the documentation?
Personally, I think it is a valuable option but do not have the skills to re-implement it.

**Comment by andrewdove1** [comment] 2019-08-19 13:18
Duplicate of issue #1679 1658

**Closed by andrewdove1** 2019-08-19 13:18 UTC
